# Generated by Django 6.0.3 on 2026-04-05 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Type of transaction', max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('food', 'Food'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('investment', 'Investment'), ('other', 'Other')], help_text='Category of the transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12)),
                ('date', models.DateField(help_text='Date of the transaction')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this financial record', on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
