# Generated by Django 6.0.3 on 2026-04-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupees (₹)')], default='INR', help_text='Currency type (currently only INR supported)', max_length=3),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount in Indian Rupees (₹)', max_digits=12),
        ),
    ]
