# Generated by Django 6.0.3 on 2026-04-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialrecord_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount in Indian Rupees (Rs)', max_digits=12),
        ),
    ]
